language: ruby
sudo: false
before_install: gem install bundler
matrix:
  allow_failures:
    - rvm: jruby-head
  fast_finish: true
  include:
    - rvm: 2.0.0
      gemfile: Gemfile
    - rvm: 2.1.10
      gemfile: Gemfile
    - rvm: 2.2.6
      gemfile: Gemfile
    - rvm: 2.3.3
      gemfile: Gemfile
    - rvm: 2.4.0
      gemfile: Gemfile
    - rvm: jruby-head
      gemfile: Gemfile
script: bundle exec rake travis:ci
notifications:
  email: false
addons:
  code_climate:
    repo_token: 44bcd04b60228fc94f2be3a5e0346441b5ea156e94e89a17fc24c5d3de483721

